lib/Auth/index.js, lib/CoreError.js, lib/Services/cayenne.js, typedefs.js
Adds support for caching. For now caching is only limited to device types
=> feat: caching plugin support

lib/Services/cayenne.js
https://mydevices.atlassian.net/browse/SS-4011
=> feat: device replace

lib/Services/delorean-es.js
Expose /state API to front-end.
=> Fix: add channel state api

lib/Services/cayenne.js
https://mydevices.atlassian.net/browse/SS-4569
=> feat: datatypes v2 retrieval

lib/Auth/index.js, lib/Services/delorean-es.js
https://mydevices.atlassian.net/browse/SS-4946
https://github.com/myDevicesIoT/tina-api/pull/727
=> feat: stream data from request

lib/Services/cayenne.js
Previously channels endpoint was called
=> Fix: meta should delete meta endpoint

lib/Services/hermes.js
Adding Create, get, delete endpoints for Hermes delete.
=> feat: exposing Hermes blacklist endpoints for gdpr issue

lib/Services/executor.js
Pass rule_ids and fields to Executor to reduce payload size and reduce number of requests.
=> feat(executor): add query param to getRules fn

lib/Services/timekeeper.js
=> Fix: add timekeeper move users endpoint

lib/Services/cayenne.js, lib/Services/executor.js, lib/Services/hermes.js, lib/Services/timekeeper.js
Need to increase timeout of request.
Staging rules db is slow. It took 200000ms on staging to finish the executor related migration.
=> Fix: change move user endpoint timeout

.eslintrc.json, lib/Request.js, package-lock.json, package.json
- Forward service error message, eg. Prometheus throwing `Boom.badRequest('some message')`.
=> fix: forward service error message

.eslintrc.json, lib/Request.js, package-lock.json, package.json
- Remove optional chaining and Node 14 requirement
=> fix: refactor error message forwarding

lib/Services/cayenne.js
https://mydevices.atlassian.net/browse/SS-7254
=> Feat: get all attribute groups from cayenne api

lib/Services/executor.js
https://mydevices.atlassian.net/browse/SS-7418
=> feat: search rules

lib/Services/cayenne.js
https://mydevices.atlassian.net/browse/SS-7315
=> feat: search integrations

lib/Services/executor.js
https://mydevices.atlassian.net/browse/SS-8608
=> feat: searchRulesWithFilters

lib/Services/cayenne.js, lib/Services/delorean-es.js, lib/Services/executor.js, lib/Services/hermes.js, lib/Services/timekeeper.js
FEAT migrate admin users
https://mydevices.atlassian.net/browse/SS-8788
=> feat: replace admin user

lib/Core.js, lib/Services/clio.js, lib/index.js
https://mydevices.atlassian.net/browse/SS-9759
=> feat: endpoint call clio from tina-api to validate formula

lib/Services/delorean-es.js
https://mydevices.atlassian.net/jira/servicedesk/projects/CS/queues/custom/68/CS-9547
=> fix: increase delorean timeouts

lib/Services/hermes.js, package-lock.json, package.json
=> fix: bump superagent version

lib/Services/delorean-es.js
/chart call added for devices: https://mydevices.atlassian.net/browse/SS-10801
Pending: https://mydevices.atlassian.net/browse/SS-9415
=> feat: device chart endpoint
